### ISSUE TITLE
Chrome Extension is at version 1.1

### ISSUE THREAD

**Issue by Ronsku** [lazyd3v/vivino-systembolaget#9]
Hi,

Chrome Extension is at version 1.1. This repository is at 1.0.2. Just a quick test caused my requests to vivino to return status code 429 (too many requests) while your 1.1 version up on chrome extension store queries algolia instead of vivino directly.

Do you mind sharing what you've done here in the version 1.1?

Thanks a bunch and cool workaround for sure!

**Comment by lazyd3v** [comment]
If you're talking about [this extension](https://chrome.google.com/webstore/detail/vivino-rating-for-systemb/lpnfmgjfljmhengiiigfkbkfgofdomgf), it's not published by me and have no idea what's done there :)

**Comment by Ronsku** [comment]
Aah yes, @lazyd3v. I was talking about that extension. I see, it's done in a different way somehow that has a workaround around the 429 too may requests limit.

Thanks anyway for the very fast response and have a great new year!

**Comment by sabatale** [comment]
Maybe @ilyamkin will help. If it has anything to do with Algolia, the data is probably pooled/hosted.
